public enum MoveMessage {
    INVALID_PATH_KNIGHT,
    INVALID_PATH_ROOK,
    INVALID_PATH_BISHOP,
    INVALID_PATH_QUEEN,
    INVALID_PATH_KING,
    INVALID_PATH_PAWN,
    CAPTURE_OWN_PIECE,
    CAPTURE_SPACE_UNOCCUPIED
}
